### ISSUE TITLE
Doesn't work with ssl?

### ISSUE THREAD

**Issue by sokoow** [Vaelor/errbot-mattermost-backend#25]
I get this when I'm trying to connect to my ssl servers:

```
2017-08-19 09:33:22,888 INFO     errbot.specific_plugin_manager storage search paths {'/usr/local/lib/python3.5/dist-packages/errbot/storage'}
2017-08-19 09:33:22,896 INFO     errbot.specific_plugin_manager Found those plugings available:
2017-08-19 09:33:22,897 INFO     errbot.specific_plugin_manager             Memory  (/usr/local/lib/python3.5/dist-packages/errbot/storage/memory.py)
2017-08-19 09:33:22,898 INFO     errbot.specific_plugin_manager              Shelf  (/usr/local/lib/python3.5/dist-packages/errbot/storage/shelf.py)
2017-08-19 09:33:22,899 INFO     errbot.bootstrap          Found Storage plugin: 'Shelf'
Description: This is the storage plugin for the traditional shelf store for errbot.
2017-08-19 09:33:22,900 DEBUG    errbot.specific_plugin_manager Refilter the plugins...
2017-08-19 09:33:22,903 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.5/dist-packages/errbot/storage/memory.plug'  rejected by strategy 'SpecificBackendLocator'
2017-08-19 09:33:22,907 DEBUG    errbot.specific_plugin_manager Load the one remaining...
2017-08-19 09:33:22,912 DEBUG    errbot.specific_plugin_manager Class to load ShelfStoragePlugin
2017-08-19 09:33:22,913 DEBUG    errbot.storage            Opening storage 'repomgr'
2017-08-19 09:33:22,914 DEBUG    errbot.storage.shelf      Open shelf storage /opt/puczat-errbot/data/repomgr.db
2017-08-19 09:33:22,923 DEBUG    errbot.storage            Opening storage 'core'
2017-08-19 09:33:22,924 DEBUG    errbot.storage.shelf      Open shelf storage /opt/puczat-errbot/data/core.db
2017-08-19 09:33:22,933 INFO     errbot.specific_plugin_manager backends search paths {'/usr/local/lib/python3.5/dist-packages/errbot/backends', '/opt/puczat-errbot/errbot-mattermost-backend'}
2017-08-19 09:33:22,966 INFO     errbot.specific_plugin_manager Found those plugings available:
2017-08-19 09:33:22,967 INFO     errbot.specific_plugin_manager              Slack  (/usr/local/lib/python3.5/dist-packages/errbot/backends/slack.py)
2017-08-19 09:33:22,968 INFO     errbot.specific_plugin_manager                IRC  (/usr/local/lib/python3.5/dist-packages/errbot/backends/irc.py)
2017-08-19 09:33:22,969 INFO     errbot.specific_plugin_manager            Graphic  (/usr/local/lib/python3.5/dist-packages/errbot/backends/graphic.py)
2017-08-19 09:33:22,970 INFO     errbot.specific_plugin_manager            Hipchat  (/usr/local/lib/python3.5/dist-packages/errbot/backends/hipchat.py)
2017-08-19 09:33:22,971 INFO     errbot.specific_plugin_manager               XMPP  (/usr/local/lib/python3.5/dist-packages/errbot/backends/xmpp.py)
2017-08-19 09:33:22,972 INFO     errbot.specific_plugin_manager               Text  (/usr/local/lib/python3.5/dist-packages/errbot/backends/text.py)
2017-08-19 09:33:22,973 INFO     errbot.specific_plugin_manager           Telegram  (/usr/local/lib/python3.5/dist-packages/errbot/backends/telegram_messenger.py)
2017-08-19 09:33:22,975 INFO     errbot.specific_plugin_manager               Test  (/usr/local/lib/python3.5/dist-packages/errbot/backends/test.py)
2017-08-19 09:33:22,976 INFO     errbot.specific_plugin_manager               Null  (/usr/local/lib/python3.5/dist-packages/errbot/backends/null.py)
2017-08-19 09:33:22,977 INFO     errbot.specific_plugin_manager         Mattermost  (/opt/puczat-errbot/errbot-mattermost-backend/mattermost.py)
2017-08-19 09:33:22,978 INFO     errbot.bootstrap          Found Backend plugin: 'Mattermost'
                                                Description: A Mattermost backend for errbot.
2017-08-19 09:33:22,979 DEBUG    errbot.specific_plugin_manager Refilter the plugins...
2017-08-19 09:33:22,982 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.5/dist-packages/errbot/backends/slack.plug'  rejected by strategy 'SpecificBackendLocator'
2017-08-19 09:33:22,984 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.5/dist-packages/errbot/backends/irc.plug'  rejected by strategy 'SpecificBackendLocator'
2017-08-19 09:33:22,986 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.5/dist-packages/errbot/backends/graphic.plug'  rejected by strategy 'SpecificBackendLocator'
2017-08-19 09:33:22,988 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.5/dist-packages/errbot/backends/hipchat.plug'  rejected by strategy 'SpecificBackendLocator'
2017-08-19 09:33:22,990 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.5/dist-packages/errbot/backends/xmpp.plug'  rejected by strategy 'SpecificBackendLocator'
2017-08-19 09:33:22,993 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.5/dist-packages/errbot/backends/text.plug'  rejected by strategy 'SpecificBackendLocator'
2017-08-19 09:33:22,994 WARNING  yapsy                     Plugin candidate '/usr/local/lib/python3.5/dist-packages/errbot/backends/telegram_messenger.plug'  rejected by strategy 'SpecificBackendLocator'
2017-08-19 09:33:23,307 DEBUG    errbot.core               ErrBot init.
2017-08-19 09:33:23,307 DEBUG    errbot.backends.base      Backend init.
2017-08-19 09:33:23,319 DEBUG    errbot.core               created a thread pool of size 10.
2017-08-19 09:33:23,330 DEBUG    errbot.core               Initializing backend storage
2017-08-19 09:33:23,331 DEBUG    errbot.storage            Opening storage 'mattermost_backend'
2017-08-19 09:33:23,332 DEBUG    errbot.storage.shelf      Open shelf storage /opt/puczat-errbot/data/mattermost_backend.db
2017-08-19 09:33:23,341 DEBUG    errbot.plugin_manager     All plugin roots:
2017-08-19 09:33:23,341 DEBUG    errbot.plugin_manager     -> /usr/local/lib/python3.5/dist-packages/errbot/core_plugins
2017-08-19 09:33:23,344 DEBUG    errbot.plugin_manager     Add /usr/local/lib/python3.5/dist-packages/errbot/core_plugins to sys.path
2017-08-19 09:33:23,345 DEBUG    errbot.plugin_manager     -> /opt/puczat-errbot/plugins/err-example
2017-08-19 09:33:23,345 DEBUG    errbot.plugin_manager     Add /opt/puczat-errbot/plugins/err-example to sys.path
2017-08-19 09:33:23,346 DEBUG    errbot.plugin_manager     /usr/local/lib/python3.5/dist-packages/errbot/core_plugins has no requirements.txt file
2017-08-19 09:33:23,347 DEBUG    errbot.plugin_manager     /opt/puczat-errbot/plugins/err-example has no requirements.txt file
2017-08-19 09:33:23,387 DEBUG    errbot.plugins.Plugins    Logger for plugin initialized...
2017-08-19 09:33:23,391 DEBUG    errbot.plugins.CommandNotFoundFilter Logger for plugin initialized...
2017-08-19 09:33:23,394 DEBUG    errbot.plugins.Utils      Logger for plugin initialized...
2017-08-19 09:33:23,398 DEBUG    errbot.plugins.ChatRoom   Logger for plugin initialized...
2017-08-19 09:33:23,402 DEBUG    errbot.plugins.Backup     Logger for plugin initialized...
2017-08-19 09:33:23,423 DEBUG    errbot.plugins.Health     Logger for plugin initialized...
2017-08-19 09:33:23,712 INFO     errbot                    webhooks:  Flag to bind /echo to                           echo
2017-08-19 09:33:23,717 DEBUG    errbot.plugins.Webserver  Logger for plugin initialized...
2017-08-19 09:33:23,725 DEBUG    errbot.plugins.ACLs       Logger for plugin initialized...
2017-08-19 09:33:23,748 DEBUG    errbot.plugins.Flows      Logger for plugin initialized...
2017-08-19 09:33:23,755 DEBUG    errbot.plugins.VersionChecker Logger for plugin initialized...
2017-08-19 09:33:23,760 DEBUG    errbot.plugins.Help       Logger for plugin initialized...
2017-08-19 09:33:23,765 DEBUG    errbot.plugins.Example    Logger for plugin initialized...
2017-08-19 09:33:23,768 DEBUG    errbot.bootstrap          Start serving commands from the mattermost backend
2017-08-19 09:33:23,784 INFO     requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): puczat.pl
2017-08-19 09:33:24,053 DEBUG    requests.packages.urllib3.connectionpool "POST /api/v4/users/login HTTP/1.1" 200 530
2017-08-19 09:33:24,062 DEBUG    mattermostdriver.websocket {'create_at': 1489569948894, 'nickname': '', 'roles': 'system_user', 'delete_at': 0, 'username': 'sokoow-test', 'email': 'sokoowpwr@o2.pl', 'update_at': 1503134340554, 'allow_marketing': True, 'position': '', 'last_name': '', 'auth_data': '', 'last_password_update': 1503134340554, 'email_verified': True, 'locale': 'en', 'auth_service': '', 'first_name': '', 'notify_props': {'channel': 'true', 'desktop_sound': 'true', 'desktop': 'all', 'email': 'true', 'first_name': 'false', 'push': 'mention', 'mention_keys': 'sokoow-test,@sokoow-test'}, 'id': 'coae9hgnhpdy5rszk949b7imkw'}
2017-08-19 09:33:24,063 DEBUG    mattermostdriver.api      <Response [200]>
2017-08-19 09:33:24,068 INFO     requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): puczat.pl
2017-08-19 09:33:25,130 DEBUG    requests.packages.urllib3.connectionpool "GET /api/v4/teams/name/puczat HTTP/1.1" 200 301
2017-08-19 09:33:25,137 DEBUG    mattermostdriver.websocket {'create_at': 1488997841848, 'type': 'O', 'delete_at': 0, 'allowed_domains': '', 'invite_id': 'tuyyfj3ouj838cwadjni6qoxhy', 'email': 'sokoow@gmail.com', 'update_at': 1489065292949, 'company_name': '', 'name': 'puczat', 'allow_open_invite': True, 'display_name': 'puczat', 'description': '', 'id': 'xghi3hph9fdnjjq8pjkgz9rq9c'}
2017-08-19 09:33:25,143 INFO     requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): puczat.pl
2017-08-19 09:33:27,216 DEBUG    requests.packages.urllib3.connectionpool "GET /api/v4/users/me HTTP/1.1" 200 530
2017-08-19 09:33:27,228 DEBUG    mattermostdriver.websocket {'create_at': 1489569948894, 'nickname': '', 'roles': 'system_user', 'delete_at': 0, 'username': 'sokoow-test', 'email': 'sokoowpwr@o2.pl', 'update_at': 1503134340554, 'allow_marketing': True, 'position': '', 'last_name': '', 'auth_data': '', 'last_password_update': 1503134340554, 'email_verified': True, 'locale': 'en', 'auth_service': '', 'first_name': '', 'notify_props': {'channel': 'true', 'desktop_sound': 'true', 'desktop': 'all', 'email': 'true', 'first_name': 'false', 'push': 'mention', 'mention_keys': 'sokoow-test,@sokoow-test'}, 'id': 'coae9hgnhpdy5rszk949b7imkw'}
2017-08-19 09:33:27,230 DEBUG    asyncio                   Using selector: EpollSelector
2017-08-19 09:33:27,470 ERROR    errbot.backends.mattermost Error reading from RTM stream:
Traceback (most recent call last):
  File "/opt/puczat-errbot/errbot-mattermost-backend/mattermost.py", line 394, in serve_once
    loop = self.driver.init_websocket(event_handler=self.mattermost_event_handler)
  File "/usr/local/lib/python3.5/dist-packages/mattermostdriver/driver.py", line 108, in init_websocket
    loop.run_until_complete(self.websocket.connect(event_handler))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/mattermostdriver/websocket.py", line 38, in connect
    ssl=context,
  File "/usr/local/lib/python3.5/dist-packages/websockets/py35/client.py", line 19, in __await__
    return (yield from self.client)
  File "/usr/local/lib/python3.5/dist-packages/websockets/client.py", line 160, in connect
    factory, wsuri.host, wsuri.port, **kwds)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 713, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 736, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 493, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)
2017-08-19 09:33:27,479 DEBUG    errbot.backends.mattermost Triggering disconnect callback
2017-08-19 09:33:27,480 INFO     errbot.core               Disconnect callback, deactivating all the plugins.
2017-08-19 09:33:27,480 INFO     errbot.backends.base      Reconnecting in 1 seconds (0 attempted reconnections so far)
2017-08-19 09:33:28,488 INFO     requests.packages.urllib3.connectionpool Starting new HTTPS connection (1): puczat.pl
```

**Comment by Vaelor** [comment]
It should, I have been using it with nothing else but SSL.
Assuming you have a valid SSL-Certificate which is not self signed (if it is self signed, you need to set the `insecure: True` on the `BOT_IDENTITY`), I am not entirely sure, this is a pretty broad error message.

Is your webserver correctly configured for mattermost, according to the docs?
https://docs.mattermost.com/install/install-ubuntu-1604.html#configuring-nginx-as-a-proxy-for-mattermost-server

**Comment by sokoow** [comment]
Yeah, stupid me, I pointed it out to port 80 instead of 443;) Sorry for hassle

**Comment by Vaelor** [comment]
No problem, glad it is resolved! :)
