### ISSUE TITLE
cannot join a room

### ISSUE THREAD

**Issue by maxandersen** [Vaelor/errbot-mattermost-backend#33]
Not sure if i'm doing it wrong but I can't get it to join a room.

`!room join wonka` in chat or `CHAT_PRESENCE = ('wonka',)` in config both result in same error:

```
00:56:00 INFO     errbot.core               Processing command 'room_join' with parameters 'wonka' from @maxandersen
00:56:01 INFO     errbot.backends.mattermos Joining channel ~wonka
00:56:01 ERROR    errbot.core               An error happened while processing a message ("room join wonka"): Traceback (most recent call last):
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core.py", line 459, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 88, in room_join
    room.join(username=self.bot_config.CHATROOM_FN, password=password)
  File "backends/errbot-mattermost-backend/src/mattermostRoom.py", line 145, in join
    'user_id': self._bot.userid
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/mattermostdriver/endpoints/channels.py", line 92, in add_user
    self.endpoint + '/' + channel_id + '/members',
TypeError: must be str, not NoneType
"
```

one to one chat works fine.

**Comment by Vaelor** [comment]
`00:56:01 INFO     errbot.backends.mattermos Joining channel ~wonka`
Do you have a channel named wonka? You have to tell which channel to join, not which user should join the current channel.

**Comment by Vaelor** [comment]
I should defintely make that error message more clear though

**Comment by maxandersen** [comment]
Yes I have a room named Wonka. I’m writing it to err boy directly to join wonka.

**Comment by Vaelor** [comment]
Is that room public or private?
If it's a private room, you can't just join, AFAIK. That is a restriction in mattermost. The bot has to be in the channel to know it. I just took a look at the mattermost api to be sure, but it seems there is no way to get private channels you are no member of.
In this case, try to invite into a room.
For example `!room invite my-private-channel mybot`

If that is not the cause of the problem:
Which version of the mattermost backend do you use? You have to look into the .plug file, or if you cloned the git repository you can also give me the SHA - I haven't updated the .plug file until a few releases ago.

**Comment by Vaelor** [comment]
Before you try out the invite.. Wait for me to fix a bug there :-D

**Comment by Vaelor** [comment]
Ok, check if you have version `2.0.1` :-) Investigating your problem revealed another bug :-D
Inviting should now work!

Will leave that open as a bug for me to fix a few things, because for the user it is not exactly clear why join doesn't work as expected.

**Comment by maxandersen** [comment]
The chat server is chat.openshift.io - runs mattermost Version: 4.2.0

and the room are not private, just now I tried joining another room and same fail:

```
22:16:28 INFO     errbot.backends.mattermos Joining channel ~openshift
22:16:28 ERROR    errbot.core               An error happened while processing a message ("room join openshift"): Traceback (most recent call last):
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core.py", line 459, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 88, in room_join
    room.join(username=self.bot_config.CHATROOM_FN, password=password)
  File "backends/errbot-mattermost-backend/src/mattermostRoom.py", line 145, in join
    'user_id': self._bot.userid
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/mattermostdriver/endpoints/channels.py", line 92, in add_user
    self.endpoint + '/' + channel_id + '/members',
TypeError: must be str, not NoneType
"
Traceback (most recent call last):
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core.py", line 459, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 88, in room_join
    room.join(username=self.bot_config.CHATROOM_FN, password=password)
  File "backends/errbot-mattermost-backend/src/mattermostRoom.py", line 145, in join
    'user_id': self._bot.userid
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/mattermostdriver/endpoints/channels.py", line 92, in add_user
    self.endpoint + '/' + channel_id + '/members',
TypeError: must be str, not NoneType
```

...and yes, I'm now running:





* 2c44afd - (HEAD -> master, origin/master, origin/HEAD) Fix an error when trying to invite users into a room (3 hours ago, Vaelor/Vaelor)
(but thats 1.2.1 afaics?)

**Comment by maxandersen** [comment]
btw. when I do invite I get this error:

```
22:22:05 ERROR    errbot.core               An error happened while processing a message ("!room invite wonka ninja"): Traceback (most recent call last):
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core.py", line 459, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 145, in room_invite
    self.query_room(args[0]).invite(*args[1:])
  File "backends/errbot-mattermost-backend/src/mattermostRoom.py", line 187, in invite
    raise UserDoesNotExistError('User \'{}\' not found'.format(user))
errbot.backends.base.UserDoesNotExistError: User 'ninja' not found
"
Traceback (most recent call last):
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core.py", line 459, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/Users/max/virtualenvs/errbot-ve/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 145, in room_invite
    self.query_room(args[0]).invite(*args[1:])
  File "backends/errbot-mattermost-backend/src/mattermostRoom.py", line 187, in invite
    raise UserDoesNotExistError('User \'{}\' not found'.format(user))
errbot.backends.base.UserDoesNotExistError: User 'ninja' not found
```

user 'ninja' is the username of the bot.

**Comment by Vaelor** [comment]
That is very strange. I will have a look into it tomorrow again. 
Version looks good!

Can you give your bot admin privileges and try it again (try team/system admin both)?
Do you have multiple teams/are channel and bot members on different teams?

**Comment by maxandersen** [comment]
I can’t give the bot admin rights. 

The bot is on same team; I’m talking with the bot both directly and in the default rooms every user get added to. I can also use MatterMost UI to invite the bot and it works - it’s only when the bot itself tries to join a room it fails.

**Comment by Vaelor** [comment]
Had the same problem without admin rights, for some reason the channelid was not available in this case.
I fixed it in my case, I can now join and invite to rooms without admin rights.

Not 100% sure there aren't any other cases like this! Hope the last version fixes it for you and sorry for the inconvience!

**Comment by maxandersen** [comment]
yay! latest version fixed it - thanks!

**Comment by Vaelor** [comment]
Glad to hear! :-)
